services:
  snowmail:
    restart: always
    build:
      context: .
    image: truewinter/snowmail
    ports:
      - 8025:8025
    volumes:
      - ./data/plugins:/app/plugins
    depends_on:
      mongo:
        condition: service_healthy
      smtp:
        condition: service_started
    environment:
      # Either modify the APP_SECRET and EMAIL_FROM here or in a .env file
      - APP_SECRET=${APP_SECRET}
      - EMAIL_FROM=${EMAIL_FROM}
      - MONGO_DB=mongodb://mongo:27017
      - SMTP_HOST=smtp
  mongo:
    image: mongo:7.0.8
    restart: always
    volumes:
      - ./data/mongo:/data/db
    # https://github.com/docker-library/mongo/pull/144
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongosh --quiet || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
  smtp:
    image: ixdotai/smtp:v0.5.2
    restart: always
    environment:
      - MAILNAME=${MAILNAME}
      - DKIM_KEY_PATH=/opt/dkim/rsa.private
      # If you have Docker configured for IPv6, remove this
      - DISABLE_IPV6=true
    volumes:
      - ./data/dkim:/opt/dkim:ro
