# This workflow was created so I can create a GitHub release if a previous run failed because the CHANGELOG.md file was invalid
# This is required because Maven Central won't allow a release to be republished with the same version
name: Publish Release on GitHub only, do not publish to Docker Hub or Maven Central

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - run: mvn -B clean package
      - uses: anton-yurchenko/git-release@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: refs/tags/${{ inputs.tag }}
        with:
          args: build/*.jar
    